name: Deploy Persoonlijk to Heroku (Backend)

on:
  push:
    branches:
      - main
    paths:
      - "persoonlijk-backend/**"
      - ".github/workflows/backend-heroku.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add backend remote origin
        run: git remote add heroku-backend https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/persoonlijk-alexander.git
      - name: Deploy backend to Heroku
        run: git push heroku-backend `git subtree split --prefix persoonlijk-backend main`:refs/heads/main --force